DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE BOARD_FILE_SEQ;
DROP SEQUENCE BOARD_REPLY_SEQ;
DROP SEQUENCE BOARD_REPLY_PICTURE_SEQ;
DROP SEQUENCE BOARD_NESTED_REPLY_SEQ;
DROP SEQUENCE SCRAP_SEQ;
DROP SEQUENCE RECIPE_REPLY_SEQ;
DROP SEQUENCE RECIPE_NESTED_REPLY_SEQ;
DROP SEQUENCE RECIPE_REPLY_PHOTO_SEQ;
DROP SEQUENCE RECIPE_SEQ;
DROP SEQUENCE INGR_SEQ;
DROP SEQUENCE DIR_SEQ;
DROP SEQUENCE TAG_SEQ;
DROP SEQUENCE LOG_GRADE_SEQ;
DROP SEQUENCE LOG_FOLLOW_SEQ;


CREATE SEQUENCE RECIPE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE INGR_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE DIR_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE TAG_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE SCRAP_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE RECIPE_REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE R_NESTED_REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE R_REPLY_PHOTO_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE BOARD_FILE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE BOARD_REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE B_REPLY_PICTURE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE B_NESTED_REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE SEQUENCE LOG_GRADE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE LOG_FOLLOW_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

SELECT SEQUENCE_NAME FROM USER_SEQUENCES;