conn modu/modu

DROP TRIGGER TGR_EMAIL;
DROP TRIGGER TGR_NICKNAME;
DROP TRIGGER TGR_PROFILE_IMG;
DROP TRIGGER TGR_FILE_PRESENCE;
DROP TRIGGER TGR_BOARD_REPLY_PICTURE_PRESENCE;
DROP TRIGGER TGR_RECIPE_REPLY_PHOTO_PRESENCE;
DROP TRIGGER TGR_LOG_FOLLOW;

CREATE OR REPLACE TRIGGER TGR_EMAIL
  AFTER UPDATE OF EMAIL ON MEMBER FOR EACH ROW
  BEGIN
    UPDATE RECIPE SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE RATING SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE SCRAP SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE RECIPE_REPLY SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE RECIPE_NESTED_REPLY SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE BOARD SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE BOARD_REPLY SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
    UPDATE BOARD_NESTED_REPLY SET M_EMAIL=:new.EMAIL WHERE M_EMAIL=:old.EMAIL;
  END;
 /

 CREATE OR REPLACE TRIGGER TGR_NICKNAME
  AFTER UPDATE OF NICKNAME ON MEMBER FOR EACH ROW
  BEGIN
    UPDATE RECIPE SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
    UPDATE RECIPE_REPLY SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
    UPDATE RECIPE_NESTED_REPLY SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
    UPDATE BOARD SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
    UPDATE BOARD_REPLY SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
    UPDATE BOARD_NESTED_REPLY SET M_NICKNAME=:new.NICKNAME WHERE M_NICKNAME=:old.NICKNAME;
  END;
 /

  CREATE OR REPLACE TRIGGER TGR_PROFILE_IMG
  AFTER UPDATE OF PROFILE_IMG ON MEMBER FOR EACH ROW
  BEGIN
    UPDATE RECIPE SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
    UPDATE RECIPE_REPLY SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
    UPDATE RECIPE_NESTED_REPLY SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
    UPDATE BOARD SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
    UPDATE BOARD_REPLY SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
    UPDATE BOARD_NESTED_REPLY SET PROFILE_IMG=:new.PROFILE_IMG WHERE M_EMAIL=:new.EMAIL AND PROFILE_IMG=:old.PROFILE_IMG;
  END;
 /

  CREATE OR REPLACE TRIGGER TGR_FILE_PRESENCE
  AFTER INSERT OR UPDATE ON BOARD_FILE FOR EACH ROW
  BEGIN
    UPDATE BOARD SET FILES=1 WHERE ID =:new.B_ID;
  END;
 /

  CREATE OR REPLACE TRIGGER TGR_BOARD_REPLY_PICTURE_PRESENCE
  AFTER INSERT ON BOARD_REPLY_PICTURE FOR EACH ROW
  BEGIN
    UPDATE BOARD_REPLY SET PICTURE=1 WHERE ID =:new.BR_ID;
  END;
 /

  CREATE OR REPLACE TRIGGER TGR_RECIPE_REPLY_PHOTO_PRESENCE
  AFTER INSERT ON RECIPE_REPLY_PHOTO FOR EACH ROW
  BEGIN
    UPDATE RECIPE_REPLY SET PHOTO=1 WHERE ID =:new.RR_ID;
  END;
 /

  CREATE OR REPLACE TRIGGER TGR_LOG_FOLLOW
  AFTER INSERT ON FOLLOW
  FOR EACH ROW
  BEGIN
    INSERT INTO LOG_FOLLOW (ID,LOG_FOLLOWEE,LOG_EVENT) VALUES(LOG_FOLLOW_SEQ.nextval, :new.FOLLOWEE,:new.M_EMAIL||'´ÔÀÌ È¸¿ø´ÔÀ» ÆÈ·Î¿ì Çß½À´Ï´Ù.');
  END;
 /
SELECT TRIGGER_NAME FROM USER_TRIGGERS;