DROP TRIGGER TGR_REPLY_PLUS_RECIPE_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_PLUS_RECIPE_REPLY
AFTER INSERT ON RECIPE_REPLY
FOR EACH ROW
BEGIN
  UPDATE RECIPE SET REPLY=REPLY+1 WHERE ID =: new.R_ID;
END;
/

DROP TRIGGER TGR_REPLY_PLUS_RECIPE_NESTED_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_PLUS_RECIPE_NESTED_REPLY
AFTER INSERT ON RECIPE_NESTED_REPLY
FOR EACH ROW
DECLARE
  R_ID NUMBER;
BEGIN
  SELECT R_ID INTO R_ID FROM RECIPE_REPLY WHERE ID =: new.RR_ID;
  UPDATE RECIPE SET REPLY=REPLY+1 WHERE ID=R_ID;
END;
/

DROP TRIGGER TGR_REPLY_MINUS_RECIPE_NESTED_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_MINUS_RECIPE_NESTED_REPLY
AFTER DELETE ON RECIPE_NESTED_REPLY
FOR EACH ROW
DECLARE
  R_ID NUMBER;
BEGIN
  SELECT R_ID INTO R_ID FROM RECIPE_REPLY WHERE ID =: old.RR_ID;
  UPDATE RECIPE SET REPLY=REPLY-1 WHERE ID=R_ID;
END;
/

DROP TRIGGER TGR_REPLY_PLUS_BOARD_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_PLUS_BOARD_REPLY
AFTER INSERT ON BOARD_REPLY
FOR EACH ROW
BEGIN
  UPDATE BOARD SET REPLY=REPLY+1 WHERE ID =: new.B_ID;
END;
/

DROP TRIGGER TGR_REPLY_PLUS_BOARD_NESTED_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_PLUS_BOARD_NESTED_REPLY
AFTER INSERT ON BOARD_NESTED_REPLY
FOR EACH ROW
DECLARE
  B_ID NUMBER;
BEGIN
  SELECT B_ID INTO B_ID FROM BOARD_REPLY WHERE ID =: new.BR_ID;
  UPDATE BOARD SET REPLY=REPLY+1 WHERE ID=B_ID;
END;
/

DROP TRIGGER TGR_REPLY_MINUS_BOARD_NESTED_REPLY;
CREATE OR REPLACE TRIGGER TGR_REPLY_MINUS_BOARD_NESTED_REPLY
AFTER DELETE ON BOARD_NESTED_REPLY
FOR EACH ROW
DECLARE
  B_ID NUMBER;
BEGIN
  SELECT B_ID INTO B_ID FROM BOARD_REPLY WHERE ID =: old.BR_ID;
  UPDATE BOARD SET REPLY=REPLY-1 WHERE ID=B_ID;
END;
/
